package com.nervz.movementtrainer.gfx

// GENERATED by model/gen_tpose.py — axis-angle (deg, x, y, z) per group that
// straightens the authored pose into a symmetric T-pose reference.
val MOKUJIN_TPOSE: Map<String, FloatArray> = mapOf(
    "UARM_A" to floatArrayOf(73.907f, 0.00000f, 0.42072f, -0.90719f),
    "FARM_A" to floatArrayOf(66.173f, 0.44765f, -0.82065f, 0.35516f),
    "UARM_B" to floatArrayOf(51.586f, 0.00000f, 0.29334f, 0.95601f),
    "FARM_B" to floatArrayOf(105.875f, 0.14487f, 0.00998f, -0.98940f),
    "THIGH_A" to floatArrayOf(40.072f, 0.91488f, 0.00000f, 0.40373f),
    "SHIN_A" to floatArrayOf(47.195f, -0.99023f, 0.12549f, -0.06086f),
    "FOOT_A" to floatArrayOf(17.697f, -0.29528f, 0.09789f, -0.95038f),
    "THIGH_B" to floatArrayOf(37.418f, 0.43018f, 0.00000f, -0.90274f),
    "SHIN_B" to floatArrayOf(57.101f, -0.58782f, -0.06220f, 0.80659f),
    "FOOT_B" to floatArrayOf(25.259f, 0.61590f, -0.02759f, -0.78734f),
)
