package com.nervz.movementtrainer.gfx

// GENERATED by model/gen_rig.py from mokujin_parts.json — do not hand-edit numbers.
// Side A = model-space x<0, side B = x>0 (anatomical mapping verified visually).
class RigGroup(
    val name: String,
    val parent: String?,
    val pivot: FloatArray,
    val nodes: List<String>,
)

val MOKUJIN_RIG: List<RigGroup> = listOf(
    RigGroup(
        "TORSO", null,
        floatArrayOf(0.0f, 0.92f, 0.0f),
        listOf("Cube.009_Mokujin_0_A", "Cube.009_Mokujin_0_B", "Cube.011_Mokujin_0_A", "Cube.011_Mokujin_0_B", "Cylinder.015_Mokujin_0_P0", "Cylinder.015_Mokujin_0_P1", "Cylinder.015_Mokujin_0_P2"),
    ),
    RigGroup(
        "HEAD", "TORSO",
        floatArrayOf(0.0f, 1.4674f, -0.0f),
        listOf("Cube.008_Mokujin_0", "Cylinder.008_Mokujin_0_P0", "Cylinder.008_Mokujin_0_P1", "Cylinder.008_Mokujin_0_P2", "Cylinder.008_Mokujin_0_P3", "Cylinder.008_Mokujin_0_P4", "Cylinder.016_Mokujin_0_P0", "Cylinder.016_Mokujin_0_P1", "Cylinder.016_Mokujin_0_P2", "Plane.002_Mokujin_0", "Plane.003_Mokujin_0"),
    ),
    RigGroup(
        "UARM_A", "TORSO",
        floatArrayOf(-0.2341f, 1.4142f, 0.0019f),
        listOf("Cube.012_Mokujin_0_A", "Cylinder.009_Mokujin_0_P0", "Cylinder.009_Mokujin_0_P1", "Cylinder.009_Mokujin_0_P2", "Torus.001_Mokujin_0_P10", "Torus.001_Mokujin_0_P9"),
    ),
    RigGroup(
        "FARM_A", "UARM_A",
        floatArrayOf(-0.3109f, 1.1727f, -0.1101f),
        listOf("Cube.013_Mokujin_0_A", "Cylinder.013_Mokujin_0_P0", "Cylinder.013_Mokujin_0_P1", "Cylinder.013_Mokujin_0_P2", "Torus.001_Mokujin_0_P0", "Torus.001_Mokujin_0_P1", "Torus.001_Mokujin_0_P2", "Torus.001_Mokujin_0_P3", "Torus.001_Mokujin_0_P4", "Torus.001_Mokujin_0_P5", "Torus.001_Mokujin_0_P6", "Torus.001_Mokujin_0_P7", "Torus.001_Mokujin_0_P8"),
    ),
    RigGroup(
        "UARM_B", "TORSO",
        floatArrayOf(0.2294f, 1.4294f, -0.0f),
        listOf("Cube.012_Mokujin_0_B", "Cylinder.014_Mokujin_0_P0", "Cylinder.014_Mokujin_0_P1", "Cylinder.014_Mokujin_0_P2", "Torus.010_Mokujin_0_P7", "Torus.010_Mokujin_0_P8", "Torus.010_Mokujin_0_P9"),
    ),
    RigGroup(
        "FARM_B", "UARM_B",
        floatArrayOf(0.4016f, 1.2218f, 0.0637f),
        listOf("Cube.013_Mokujin_0_B", "Cylinder.013_Mokujin_0_P3", "Cylinder.013_Mokujin_0_P4", "Cylinder.013_Mokujin_0_P5", "Torus.010_Mokujin_0_P4", "Torus.010_Mokujin_0_P5", "Torus.010_Mokujin_0_P6"),
    ),
    RigGroup(
        "THIGH_A", null,
        floatArrayOf(-0.108f, 0.8632f, 0.0441f),
        listOf("Cube.010_Mokujin_0_A", "Cylinder.012_Mokujin_0_P0", "Cylinder.012_Mokujin_0_P1", "Cylinder.012_Mokujin_0_P2", "Torus.003_Mokujin_0_P0", "Torus.003_Mokujin_0_P1", "Torus.003_Mokujin_0_P10", "Torus.003_Mokujin_0_P2", "Torus.003_Mokujin_0_P3", "Torus.003_Mokujin_0_P4", "Torus.003_Mokujin_0_P5", "Torus.003_Mokujin_0_P6", "Torus.003_Mokujin_0_P7", "Torus.003_Mokujin_0_P8", "Torus.003_Mokujin_0_P9"),
    ),
    RigGroup(
        "SHIN_A", "THIGH_A",
        floatArrayOf(-0.214f, 0.5511f, 0.2843f),
        listOf("Cube.007_Mokujin_0_A", "Cylinder.011_Mokujin_0_P0", "Cylinder.011_Mokujin_0_P1", "Cylinder.011_Mokujin_0_P2", "Torus.002_Mokujin_0_P2", "Torus.002_Mokujin_0_P3", "Torus.002_Mokujin_0_P4"),
    ),
    RigGroup(
        "FOOT_A", "SHIN_A",
        floatArrayOf(-0.3258f, 0.0999f, 0.1982f),
        listOf("Cylinder.010_Mokujin_0_P0", "Cylinder.010_Mokujin_0_P1", "Cylinder.010_Mokujin_0_P2", "Cylinder.010_Mokujin_0_P3", "Torus.002_Mokujin_0_P0", "Torus.002_Mokujin_0_P1"),
    ),
    RigGroup(
        "THIGH_B", null,
        floatArrayOf(0.1247f, 0.8632f, -0.055f),
        listOf("Cube.010_Mokujin_0_B", "Cylinder.012_Mokujin_0_P3", "Cylinder.012_Mokujin_0_P4", "Cylinder.012_Mokujin_0_P5", "Cylinder.012_Mokujin_0_P6", "Torus.008_Mokujin_0_P0", "Torus.008_Mokujin_0_P1", "Torus.008_Mokujin_0_P10", "Torus.008_Mokujin_0_P11", "Torus.008_Mokujin_0_P2", "Torus.008_Mokujin_0_P3", "Torus.008_Mokujin_0_P4", "Torus.008_Mokujin_0_P5", "Torus.008_Mokujin_0_P6", "Torus.008_Mokujin_0_P7", "Torus.008_Mokujin_0_P8", "Torus.008_Mokujin_0_P9", "Torus.010_Mokujin_0_P0", "Torus.010_Mokujin_0_P1", "Torus.010_Mokujin_0_P2", "Torus.010_Mokujin_0_P3"),
    ),
    RigGroup(
        "SHIN_B", "THIGH_B",
        floatArrayOf(0.3484f, 0.5393f, 0.0516f),
        listOf("Cube.007_Mokujin_0_B", "Cylinder.011_Mokujin_0_P3", "Cylinder.011_Mokujin_0_P4", "Cylinder.011_Mokujin_0_P5", "Torus.009_Mokujin_0_P2", "Torus.009_Mokujin_0_P3", "Torus.009_Mokujin_0_P4"),
    ),
    RigGroup(
        "FOOT_B", "SHIN_B",
        floatArrayOf(0.2493f, 0.0995f, -0.091f),
        listOf("Cylinder.010_Mokujin_0_P10", "Cylinder.010_Mokujin_0_P4", "Cylinder.010_Mokujin_0_P5", "Cylinder.010_Mokujin_0_P6", "Cylinder.010_Mokujin_0_P7", "Cylinder.010_Mokujin_0_P8", "Cylinder.010_Mokujin_0_P9", "Torus.009_Mokujin_0_P0", "Torus.009_Mokujin_0_P1"),
    ),
)
